### ISSUE TITLE
Undefined variable in `if test=""`

### ISSUE THREAD

**Issue by Geczy** [jsplumb/rotors#17]
```html
<r-if test="fbm_connect">
  <p>It's connected to fbm!</p>
</r-if>
```

If I do this, and the variable doesn't exist, then the whole jsplumb rendering fails 

It should fail silently and continue. But an undefined variable will fail the whole site

**Comment by Geczy** [comment]
It should allow for testing against undefined variables without causing exceptiosn

**Comment by sporritt** [comment]
you can use `typeof` for this one: 

```
<r-if test="typeof fbm_connect !== 'undefined'">
...
</r-if>
```
